sudo: required
services:
 - docker
git:
  lfs_skip_smudge: true
branches:
  except:
  - gh-pages
language: node_js
before_install: cd src/tiler
install: yarn install
before_script: yarn transpile
script: yarn test
deploy:
  - provider: script
    skip-cleanup: true
    script: cd ../.. && bash scripts/deploy-demo.sh
    on:
      branch: develop
