sudo: required
services:
 - docker
git:
  lfs_skip_smudge: true
branches:
  except:
  - gh-pages
before_install: echo PROJECT_NAME=test > .env && echo LAMBDA_REGION=us-east-1 >> .env
install: docker-compose build --pull tiler
script: scripts/test
deploy:
  - provider: script
    skip-cleanup: true
    script: bash scripts/deploy-demo.sh
    on:
      branch: develop
