#!/bin/bash

yarn claudia update --no-optional-dependencies \
   ${LAMBDA_TIMEOUT:+--timeout ${LAMBDA_TIMEOUT}} \
   ${LAMBDA_MEMORY:+--memory ${LAMBDA_MEMORY}} \
   ${LAMBDA_SECURITY_GROUPS:+--security-group-ids ${LAMBDA_SECURITY_GROUPS}} \
   ${LAMBDA_SUBNETS:+--subnet-ids ${LAMBDA_SUBNETS}}
