#!/bin/bash

yarn claudia create --no-optional-dependencies --api-module src/api \
    --name ${PROJECT_NAME} --region ${LAMBDA_REGION} \
    ${LAMBDA_ROLE:+--role ${LAMBDA_ROLE}} \
    ${LAMBDA_TIMEOUT:+--timeout ${LAMBDA_TIMEOUT}} \
    ${LAMBDA_MEMORY:+--memory ${LAMBDA_MEMORY}} \
    ${LAMBDA_SECURITY_GROUPS:+--security-group-ids ${LAMBDA_SECURITY_GROUPS}} \
    ${LAMBDA_SUBNETS:+--subnet-ids ${LAMBDA_SUBNETS}} \
    --set-env TILEGARDEN_DB_HOST=${TILEGARDEN_DB_HOST},TILEGARDEN_DB_NAME=${TILEGARDEN_DB_NAME},TILEGARDEN_DB_PASSWORD=${TILEGARDEN_DB_PASSWORD},TILEGARDEN_DB_PORT=${TILEGARDEN_DB_PORT},TILEGARDEN_DB_USER=${TILEGARDEN_DB_USER} \
&& yarn parse-id
