version: '2.1'
services:
  windshaft:
    build:
      context:
        .
      dockerfile: Dockerfile-windshaft
    image: quay.io/azavea/windshaft:latest
    depends_on:
      redis:
        condition:
          service_started
      database:
        condition: service_started
    # run server entrypoint script on startup
    command: "server/server.js"
    volumes:
      # map this directory's server folder to
      # /opt/windshaft/server on the container
      - ${PWD}/windshaft:/opt/windshaft/server
    ports:
      # serve port 5000 on the container as port 5000 on the machine
      - "5000:5000"
  database:
    image: quay.io/azavea/postgis:2.3-postgres9.6-slim
    expose:
      # expose port 5432 to other containers in docker-compose
      - "5432"
  redis:
    image: redis:3.2
    expose:
    - "6379"
