#!/bin/bash

set -e

function usage() {
    echo -n "Usage: $(basename "$0")
Pulls and builds container images using docker-compose.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        # Build containers.
        docker-compose -f docker-compose.yml build
    fi
fi
