#!/bin/bash

set -e

function usage() {
    echo -n "Usage: $(basename "${0}") SERVICE
Login to a running Docker container's shell.
Options:
    --help      Display this help text
"
}

function main() {

    if [ "${1}" = "database" ]
    then
        docker-compose exec -u postgres database psql -d postgres
    else
        docker-compose exec ${1} bash
    fi
}


if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        SERVER_COMMAND=${1:-start}
        main $SERVER_COMMAND
    fi
    exit
fi
