#!/usr/bin/env bash

set -e

DEPLOY_NEW=""
NO_CACHE=""

function usage() {
    echo -n "Usage: $(basename "${0}") [OPTION]
Deploys a Tilegarden instance to AWS by building docker containers first
Options:
    --help        Show usage
    --new        Deploy as a new lambda
    --no-cache    Don't use cache when building containers
"
    exit 0
}

function main() {
    if [[ $DEPLOY_NEW != "--new" && ! -f ./src/tiler/claudia.json ]]; then
        echo "No existing deployment found to update! (did you mean to use '--new'?)"
        exit 1
    fi

    docker-compose build --pull terraform

    docker-compose -f docker-compose.yml \
                   build --pull ${NO_CACHE:+$NO_CACHE} tiler

    ./scripts/publish ${DEPLOY_NEW:+$DEPLOY_NEW}
}


if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    # handle command line arguments
    # modified from https://stackoverflow.com/a/7069755
    while [ $# -gt 0 ]; do
        case "$1" in
            -n| --new)
                DEPLOY_NEW='--new'
                shift
                ;;
            --no-cache)
                NO_CACHE='--no-cache'
                shift
                ;;
            -h| --help| *)
                usage
                ;;
        esac
    done

    main
fi

