#!/bin/bash

set -e

function usage() {
    echo -n "Usage: $(basename "${0}")
Removes all published resources from AWS
Options:
    --help      Display this help text
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        docker-compose run tiler destroy
    fi
    exit
fi
