#!/bin/bash

set -e

function usage() {
    echo -n "Usage: $(basename "${0}") [OPTION]
Publish lambdas to AWS Lambda
Options:
    --new     Deploy as a new lambda
    --help      Display this help text
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        docker-compose run --rm tiler deploy "${1}"
    fi
    exit
fi
