#!/bin/bash
set -eu


function usage() {
    echo -n \
"Usage: $(basename $0) [COMMAND]

Start/stop/restart/get status of services.

COMMAND can be one of [start, stop, restart, status]. Default is start.
"
}


function main() {
    SERVICES='tiler database'
    DC_COMMAND='docker-compose --env-file .env.local'
    if [ "${1}" = "start" ]
    then
        ${DC_COMMAND} up ${SERVICES}
    elif [ "${1}" = "stop" ]
    then
        ${DC_COMMAND} stop ${SERVICES}
    elif [ "${1}" = "restart" ]
    then
        ${DC_COMMAND} restart ${SERVICES}
    elif [ "${1}" = "status" ]
    then
        ${DC_COMMAND} ps
    else
        echo "Unknown option ${1}! Must be one of [start, stop, restart, status ]."
        exit 1
    fi
}


if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        SERVER_COMMAND=${1:-start}
        main $SERVER_COMMAND
    fi
    exit
fi
