#!/bin/bash

set -e

function usage() {
    echo -n "Usage: $(basename "$0")
Builds and pulls container images using docker-compose.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        # Build containers.
        docker-compose build --pull

        # Download sample data if flag is set
        if [ "${1:-}" = "--download" ]
        then
            ./scripts/fetch-data.sh
        fi

        # Launch database container so we can populate it.
        docker-compose up -d database
        docker-compose exec database bash -c "./load_sample_data > /dev/null"
    fi
fi
