#!/bin/bash

set -e

function usage() {
    echo -n "Usage: $(basename "${0}")
Removes all published resources from AWS
Options:
    --help      Display this help text
"
}

function main() {
	echo "WARNING: you are about to destroy all your deployed resources!"
	read -p "If this is what you want, type 'yes' to continue: " -r
	echo
	if [[ $REPLY =~ ^[yY][eE][sS]$ ]]
	then

		# Destroy deployed resources
		# This command ALSO tried to destroy your lambda's IAM role.
		# It will probably fail to do so, but it will delete the lambda
		# and API Gateway FIRST, so it's fine.
		docker-compose run tiler yarn destroy || true;
		docker-compose run -e TF_VAR_source_id=$(<src/tiler/.api-id) terraform destroy -auto-approve;

		# Remove local config files
		docker-compose run tiler rm claudia.json .api-id;
		docker-compose run --entrypoint rm terraform -rf .terraform terraform.tfstate terraform.tfstate.backup;

	else
		echo "Aborting destroy"
	fi
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        main
    fi
    exit
fi
