#!/bin/bash

set -e

function usage() {
    echo -n "Usage: $(basename "${0}") [OPTION]
Publish lambdas to AWS Lambda
Options:
    --new     Deploy as a new lambda
    --help      Display this help text
"
}

function checkJQ() {
	if ! [ -x "$(command -v jq)" ]
	then
		echo "jq not found!";
		echo "Please install jq to continue with deployment process (https://stedolan.github.io/jq/)";
		exit 1;
	fi

}

function main() {
    checkJQ
    if [ "${1}" = "--new" ]
    then
        docker-compose run -e NODE_ENV=production tiler yarn deploy-new;
    else
        docker-compose run -e NODE_ENV=production tiler yarn deploy;
    fi

	# Deploy CloudFront proxy
	docker-compose run -e TF_VAR_source_id=$(jq -r '.api.id' src/tiler/claudia.json) terraform apply -auto-approve;
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        SERVER_COMMAND=${1:-start}
        main $SERVER_COMMAND
    fi
    exit
fi
