#!/bin/bash

set -e

function usage() {
    echo -n "Usage: $(basename "${0}") [OPTION]
Login to a running Docker container's shell.
Options:
    --new     Deploy as a new lambda
    --help      Display this help text
"
}

function main() {
#   TODO: Append "-- --set-env POSTGRES_PASSWORD=${TILEGARDEN_PASSWORD}"
#   TODO: to the end of the deployment calls to set the password in
#   TODO: AWS, if necessary
    if [ "${1}" = "--new" ]
    then
        docker-compose run tiler bash -c "yarn deploy-new"
    else
        docker-compose run tiler bash -c "yarn deploy"
    fi

}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        SERVER_COMMAND=${1:-start}
        main $SERVER_COMMAND
    fi
    exit
fi
