version: '3.1'
services:
  proxy:
    image: tile-proxy
    build:
      context: ./src/proxy
      dockerfile: Dockerfile
    ports:
      - "9001:80"
    links:
      - tiler:tiler.lambnik.azavea.com

  database:
    image: quay.io/azavea/postgis:2.3-postgres9.6-slim
    expose:
      - "5432"

  tiler:
    image: tiler
    build:
      context: ./src/tiler
      dockerfile: Dockerfile
    ports:
      - "9000:3000"
      - "9229:9229"
    environment:
      - DEV_TILEGARDEN_USER=postgres
      - DEV_TILEGARDEN_PASSWORD=postgres
      - DEV_TILEGARDEN_DB=postgres
      - DEV_TILEGARDEN_HOST=database.lambnik.azavea.com
    env_file: .env
    links:
      - database:database.lambnik.azavea.com
    volumes:
      - ./src/tiler:/home/tiler
      - node_modules:/home/tiler/node_modules
      - bin:/home/tiler/bin
      - $HOME/.aws:/root/.aws:ro

  terraform:
    image: hashicorp/terraform:light
    env_file: .env
    working_dir: /home/terraform
    command: "init"
    volumes:
      - ./src/terraform:/home/terraform
      - dotterraform:/home/terraform/.terraform
      - $HOME/.aws:/root/.aws:ro

volumes:
  node_modules:
  bin:
  dotterraform:
