version: '3.1'
services:
  proxy:
    image: tile-proxy
    build:
      context: ./src/proxy
      dockerfile: Dockerfile
    ports:
      - "9001:80"
    depends_on:
      - tiler
    links:
      - tiler:tiler.lambnik.azavea.com

  database:
    image: quay.io/azavea/postgis:2.3-postgres9.6-slim
    expose:
      - "5432"

  tiler:
    image: tiler
    build:
      context: ./src/tiler
      dockerfile: Dockerfile
    ports:
      - "9000:3000"
      - "9229:9229"
    environment:
      - NODE_ENV=development
    env_file: config/aws-config.env
    links:
      - database:database.lambnik.azavea.com
    volumes:
      - ./src/tiler:/home/tiler
      - ./config/mapnik:/home/tiler/src/config
      - node_modules:/home/tiler/node_modules
      - bin:/home/tiler/bin
      - $HOME/.aws:/root/.aws:ro

volumes:
  node_modules:
  bin:
